# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170719_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
