# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='EMAIL',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
