# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170719_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(),
        ),
    ]
