# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_author_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='myapp.Author'),
        ),
    ]
