# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Publisher'),
            preserve_default=False,
        ),
    ]
