# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170720_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': '\u51fa\u7248\u793e', 'verbose_name_plural': '\u51fa\u7248\u793e'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_data',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
