# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=16, verbose_name='\u5bc6\u7801'),
            preserve_default=False,
        ),
    ]
