# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=60, verbose_name='\u5bc6\u7801'),
        ),
    ]
